### ISSUE TITLE
Photo Upload on mobile

### ISSUE THREAD

**Issue by fnowrouzi** [fnowrouzi/OrloveV1#1]
-we have problem uploading the photo on the website , on mobile device on any version 
-please eliminate the mobile version for now

![screen shot 2017-08-27 at 1 06 00 pm](https://user-images.githubusercontent.com/29559803/29752303-7000d0b2-8b29-11e7-90b9-c3886bc5e7be.png)

**Comment by AlexPilotGroup** [comment]
- mobile version buttons are commented. 

Pictures are being uploaded from our side both in desktop and mobile versions https://www.useloom.com/share/324bf6af815d4af9a95e52de6f1fd0eb
Need more details

**Comment by fnowrouzi** [comment]
- The photo upload with existing files are ok, but During the Registeration steps, it prevents that and I did on both mobile and computer
It gives this error that your profile is not up until you upload photo
![image1](https://user-images.githubusercontent.com/29559803/29783532-c4d5014c-8bee-11e7-8723-ec3be5aa0410.PNG)

**Comment by AlexPilotGroup** [comment]
Answer from the developer: there is an error with the root owner of the /var/www/html/uploads/user-logo/0/1 directory. The script doesn't have permission to create files/folders. 
And we couldn't change the owner through ssh

**Comment by fnowrouzi** [comment]
what do you need to do that?

**Comment by AlexPilotGroup** [comment]
The CTO checked it. He said that he managed to change the owner via sudo. It works from our side now.
Please check it.

**Comment by fnowrouzi** [comment]
It is working now, But I can not have access to Admin page !

**Comment by AlexPilotGroup** [comment]
The admin panel seems to be working now http://joxi.ru/l2ZELddu8NeW1m
Kindly verify it from your side.

**Comment by fnowrouzi** [comment]
-Admin panel fixed
-Log in to website on mobile is still a problem

**Comment by AlexPilotGroup** [comment]
need more details on login issue. 
tested in mobile version and desktop - worked fine.

**Comment by fnowrouzi** [comment]
-After clicking on this: https://orlovedate.com on mobile
-after click on sign in
- this is the error: safari can not open the page because too many redirects occurred.

**Comment by AlexPilotGroup** [comment]
Tested - it seems okay http://i.imgur.com/g95rB3N.png
Could you try clearing the cookies in the browser?

**Comment by fnowrouzi** [comment]
-This step is ok, but after that it dosent log in

**Comment by fnowrouzi** [comment]
It fixed if the cookies removed!
