### ISSUE TITLE
Logo in russian langauge:

### ISSUE THREAD

**Issue by fnowrouzi** [fnowrouzi/OrloveV1#7]
The logo is different. please adjust
![screen shot 2017-09-12 at 12 15 37 pm](https://user-images.githubusercontent.com/29559803/30336840-64ec0ab0-97b4-11e7-811f-d9cbfd4c22a8.png)

**Comment by AlexPilotGroup** [comment]
The logo is changed now http://joxi.ru/Vm6laMMTxbZLyA
The issue is no more relevant
