### ISSUE TITLE
please delete "Evaluate step" after registeration 

### ISSUE THREAD

**Issue by fnowrouzi** [fnowrouzi/OrloveV1#9]
- Please delete this step after registeration 
"like me"  or skip right after registeration 

![img_7860](https://user-images.githubusercontent.com/29559803/30389165-22ef768e-9880-11e7-98a1-38802d22c2fe.JPG)
![img_7861](https://user-images.githubusercontent.com/29559803/30389171-25c5e42e-9880-11e7-833a-55655317f71d.JPG)

**Comment by AlexPilotGroup** [comment]
Okay, we'll remove this step

**Comment by AlexPilotGroup** [comment]
It's changed https://www.useloom.com/share/ef5587247afa4b61bb6b59d8f5630fd4
